server:
  host: 0.0.0.0
  port: 8080
  static_directory: static
  templates_directory: templates

log:
  level: info
  output: file
  file: server.log
  directory: logs
  json: false

database:
  host: localhost
  port: 5432
  database: postgres
  user: postgres
  password: postgres

upload:
  max_size: 5000000000 # 5GB
  directory: data
