server:
  host: 0.0.0.0
  port: 8080
  static_directory: /usr/share/io.mikupush.server/static
  templates_directory: /usr/share/io.mikupush.server/templates

log:
  level: info
  output: file
  file_prefix: server
  directory: /var/log/io.mikupush.server
  json: false

database:
  host: localhost
  port: 5432
  database: postgres
  user: postgres
  password: postgres

upload:
  max_size: 5000000000 # 5GB
  directory: /var/lib/io.mikupush.server/data
