services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/srv/data
      - ./config.yaml:/srv/config.yaml:ro
    environment:
      RUST_LOG: debug
      MIKU_PUSH_DATABASE_HOST: postgres
      MIKU_PUSH_DATABASE_PORT: 5432
      MIKU_PUSH_DATABASE_NAME: miku_push
      MIKU_PUSH_DATABASE_USER: miku_push
      MIKU_PUSH_DATABASE_PASSWORD: miku_push

  postgres:
    image: postgres:17.6
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: miku_push
      POSTGRES_PASSWORD: miku_push
      POSTGRES_DB: miku_push

  swagger:
    image: swaggerapi/swagger-ui:v5.31.0
    ports:
      - "8081:8080"
    volumes:
      - "./api.yaml:/api.yaml:ro"
    environment:
      SWAGGER_JSON: /api.yaml

volumes:
  postgres:
