services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./config.yaml:/config.yaml:ro
    environment:
      RUST_LOG: debug
      MIKU_PUSH_DATABASE_HOST: postgres
      MIKU_PUSH_DATABASE_PORT: 5432
      MIKU_PUSH_DATABASE_NAME: miku_push
      MIKU_PUSH_DATABASE_USER: miku_push
      MIKU_PUSH_DATABASE_PASSWORD: miku_push

  postgres:
    image: postgres:17.6
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: miku_push
      POSTGRES_PASSWORD: miku_push
      POSTGRES_DB: miku_push

volumes:
  postgres:
